/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Milos Cvetkovic
 */
public class Igra extends javax.swing.JFrame {

//    0 za prvog, 1 za drugog
    private int igracKojiJeNaRedu = 0;

    /**
     * Creates new form Igra
     *
     * @param s
     */
    public Igra(String s) {

        initComponents();
        podesavanja(s);
        novaIgra();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlIgra = new javax.swing.JPanel();
        jScrollPaneTabelinScrollPanel = new javax.swing.JScrollPane();
        jTableTabela = new javax.swing.JTable();
        jpnlRezultat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtIgrac = new javax.swing.JTextField();
        jtxtRezultat = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOpcije = new javax.swing.JMenu();
        jMenuItemNovaIgra = new javax.swing.JMenuItem();
        jMenuItemIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XOX");

        jpnlIgra.setBorder(javax.swing.BorderFactory.createTitledBorder("Igra"));
        jpnlIgra.setToolTipText("");

        jScrollPaneTabelinScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTabelinScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneTabelinScrollPanel.setAutoscrolls(true);

        jTableTabela.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jTableTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTabela.setColumnSelectionAllowed(true);
        jTableTabela.getTableHeader().setReorderingAllowed(false);
        jTableTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaMouseClicked(evt);
            }
        });
        jScrollPaneTabelinScrollPanel.setViewportView(jTableTabela);
        jTableTabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jpnlIgraLayout = new javax.swing.GroupLayout(jpnlIgra);
        jpnlIgra.setLayout(jpnlIgraLayout);
        jpnlIgraLayout.setHorizontalGroup(
            jpnlIgraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlIgraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPaneTabelinScrollPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlIgraLayout.setVerticalGroup(
            jpnlIgraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlIgraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTabelinScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnlRezultat.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezultat"));

        jLabel1.setText("Igrac:");

        jLabel3.setText("Rezultat:");

        jtxtIgrac.setEditable(false);
        jtxtIgrac.setBackground(new java.awt.Color(204, 204, 204));
        jtxtIgrac.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtIgrac.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtIgrac.setFocusable(false);

        jtxtRezultat.setEditable(false);
        jtxtRezultat.setBackground(new java.awt.Color(204, 204, 204));
        jtxtRezultat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtRezultat.setFocusable(false);

        javax.swing.GroupLayout jpnlRezultatLayout = new javax.swing.GroupLayout(jpnlRezultat);
        jpnlRezultat.setLayout(jpnlRezultatLayout);
        jpnlRezultatLayout.setHorizontalGroup(
            jpnlRezultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlRezultatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlRezultatLayout.setVerticalGroup(
            jpnlRezultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlRezultatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlRezultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlRezultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtxtRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlRezultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtxtIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jMenuOpcije.setText("Opcije");

        jMenuItemNovaIgra.setText("Nova Igra");
        jMenuItemNovaIgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaIgraActionPerformed(evt);
            }
        });
        jMenuOpcije.add(jMenuItemNovaIgra);

        jMenuItemIzlaz.setText("Izlaz");
        jMenuItemIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzlazActionPerformed(evt);
            }
        });
        jMenuOpcije.add(jMenuItemIzlaz);

        jMenuBar.add(jMenuOpcije);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlRezultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlIgra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlRezultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlIgra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzlazActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemIzlazActionPerformed

    private void jTableTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaMouseClicked

//        Ostavio sam pod komentarom pocetan kod koji mi je pravio problem jer je
//        bilo potrebno kliknuti dvaput da bi kompjuter odigrao svoj potez.
        
//        if (igracKojiJeNaRedu == 0) {
            jTableTabela.getModel().setValueAt("X", jTableTabela.getSelectedRow(), jTableTabela.getSelectedColumn());
//            igracKojiJeNaRedu++;
            jTableTabela.clearSelection();
            if(!ai()){
                novaIgra();
                new PokusajtePonovo(this, true).setVisible(true);
            }
//        } else if (igracKojiJeNaRedu == 1) {
//            if(!ai()){
//                new PokusajtePonovo(this, true).setVisible(true);
//            }
//            ovako bilo kada bi zeleli da igramo u dva igraca
//            jTableTabela.getModel().setValueAt("O", jTableTabela.getSelectedRow(), jTableTabela.getSelectedColumn());
//            igracKojiJeNaRedu--;
//            jTableTabela.clearSelection();
//        }
        if (proveriPobedu()) {
            int rezultat = Integer.parseInt(jtxtRezultat.getText());
            rezultat++;
            jtxtRezultat.setText("" + rezultat);
            novaIgra();
            new Pobeda(this, true).setVisible(true);            
        }


    }//GEN-LAST:event_jTableTabelaMouseClicked

    private void jMenuItemNovaIgraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaIgraActionPerformed

        novaIgra();

    }//GEN-LAST:event_jMenuItemNovaIgraActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Igra().setVisible(true);
//            }
//        });
//    }

    private void novaIgra() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                jTableTabela.setValueAt("", i, j);
            }
            
        }
        igracKojiJeNaRedu = 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemIzlaz;
    private javax.swing.JMenuItem jMenuItemNovaIgra;
    private javax.swing.JMenu jMenuOpcije;
    private javax.swing.JScrollPane jScrollPaneTabelinScrollPanel;
    private javax.swing.JTable jTableTabela;
    private javax.swing.JPanel jpnlIgra;
    private javax.swing.JPanel jpnlRezultat;
    private javax.swing.JTextField jtxtIgrac;
    private javax.swing.JTextField jtxtRezultat;
    // End of variables declaration//GEN-END:variables

    private void podesavanja(String s) {
        jTableTabela.setRowHeight(100);
        TableColumn column = null;
        for (int i = 0; i < 3; i++) {
            centrirajTekstUTabeli(jTableTabela, i);
            column = jTableTabela.getColumnModel().getColumn(i);
            column.setPreferredWidth(150);
            column.setHeaderValue(null);
        }
        jtxtIgrac.setText(null);
        jtxtRezultat.setText(null);
        jtxtIgrac.setText(s);
        jtxtRezultat.setText(Integer.toString(0));
    }

    private void centrirajTekstUTabeli(JTable table, int column) {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(column).setCellRenderer(rightRenderer);
    }

    private boolean proveriPobedu() {
        
        if ((jTableTabela.getModel().getValueAt(0, 0).equals("X") && jTableTabela.getModel().getValueAt(1, 1).equals("X") && jTableTabela.getModel().getValueAt(2, 2).equals("X")) || (jTableTabela.getModel().getValueAt(0, 2).equals("X") && jTableTabela.getModel().getValueAt(1, 1).equals("X") && jTableTabela.getModel().getValueAt(2, 0).equals("X"))) {
            return true;
        }
        for (int i = 0; i < 3; i++) {
            boolean pobeda = true;
            for (int j = 0; j < 3; j++) {
                if (!jTableTabela.getModel().getValueAt(i, j).equals("X")) {
                    pobeda = false;
                }
            }
            if (pobeda) {
                return true;
            }
        }
        for (int i = 0; i < 3; i++) {
            boolean pobeda = true;
            for (int j = 0; j < 3; j++) {
                if (!jTableTabela.getModel().getValueAt(j, i).equals("X")) {
                    pobeda = false;
                }
            }
            if (pobeda) {
                return true;
            }
        }

        return false;
    }
    
    
    private boolean ai(){
//        metoda je pravljena samo da popunjava prvo slobodno mesto,
//        nije pravljena da pobedi igraca
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if(jTableTabela.getModel().getValueAt(i, j).equals("")){
                    jTableTabela.setValueAt("O", i, j);
                    return true;
                }
            }
        }
        return false;
    }
}
